INSERT INTO tb_user (name, email, password) VALUES ('Bob Black', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana White', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Documentário');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção Científica');
INSERT INTO tb_genre (name) VALUES ('Musical');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Suspense');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Thriller');

INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Toy Story','Toy Story - Um mundo de aventuras', 1995, 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/6AafgfifXkFS4g2xGJZIwsPQK6P.jpg', 'O aniversário do garoto Andy está chegando e seus brinquedos ficam nervosos, temendo que ele ganhe novos brinquedos que possam substituí-los. Liderados pelo caubói Woody, o brinquedo predileto de Andy, eles recebem Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Com ciúmes, Woody tenta ensiná-lo uma lição, mas Buzz cai pela janela. É o início da aventura do caubói, que precisa resgatar Buzz para limpar sua barra com os outros brinquedos.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Loucademia de Polícia','What an Institution', 1984, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'O prefeito resolve mudar a lei, afirmando que fatores como sexo, peso e inteligência não devem influenciar nas aplicações para a força policial. Liderado por Carey Mahoney, um grupo de jovens incompetentes, mas de bom coração, ingressa na Academia de Polícia para o desespero dos instrutores, que buscarão impedir de toda as formas as brincadeiras da turma.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Escorpião Rei','Guerreiro, Lenda, Rei', 2002, 'https://3.bp.blogspot.com/-blPP-TXQVHo/VMVOkRLcmrI/AAAAAAAAAxM/zPi9f_j_obk/s1600/filme%2Bo%2Bescorpi%C3%A3o%2Brei.jpg', 'Menom, um governante maligno, está conquistando muitos reinos com a ajuda de uma feiticeira que pode prever o sucesso ou fracasso da missão. Com isso, várias tribos inimigas se unem a fim de contratar um eficaz assassino que poderá eliminar a feiticeira. Este assassino é um acadiano, Mathayus. Com a ajuda de um ladrão de cavalos e da feiticeira, que se tornou sua aliada, eles vão combater Menom e seu exército.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Onde os fracos não tem vez','Um filme dos irmãos Cohen', 2008, 'https://br.web.img3.acsta.net/pictures/210/079/21007978_20130523175557996.jpg', 'Texas, década de 80. Um traficante de drogas é encontrado no deserto por um caçador pouco esperto, Llewelyn Moss (Josh Brolin), que pega uma valise cheia de dinheiro mesmo sabendo que em breve alguém irá procurá-lo devido a isso. Logo Anton Chigurh (Javier Bardem), um assassino psicótico sem senso de humor e piedade, é enviado em seu encalço. Porém para alcançar Moss ele precisará passar pelo xerife local, Ed Tom Bell (Tommy Lee Jones).', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Os Vingadores','The Avengers', 2012, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'Loki (Tom Hiddleston) retorna à Terra enviado pelos chitauri, uma raça alienígena que pretende dominar os humanos. Com a promessa de que será o soberano do planeta, ele rouba o cubo cósmico dentro de instalações da S.H.I.E.L.D. e, com isso, adquire grandes poderes. Loki os usa para controlar o dr. Erik Selvig (Stellan Skarsgard) e Clint Barton/Gavião Arqueiro (Jeremy Renner), que passam a trabalhar para ele. No intuito de contê-los, Nick Fury (Samuel L. Jackson) convoca um grupo de pessoas com grandes habilidades, mas que jamais haviam trabalhado juntas: Tony Stark/Homem de Ferro (Robert Downey Jr.), Steve Rogers/Capitão América (Chris Evans), Thor (Chris Hemsworth), Bruce Banner/Hulk (Mark Ruffalo) e Natasha Romanoff/Viúva Negra (Scarlett Johansson). Só que, apesar do grande perigo que a Terra corre, não é tão simples assim conter o ego e os interesses de cada um deles para que possam agir em grupo.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Bohemian Rhapsody','A única coisa mais extraordinária do que a sua música é a sua história', 2018, 'http://br.web.img3.acsta.net/c_310_420/pictures/18/08/24/21/29/2341995.jpg', 'Freddie Mercury (Rami Malek) e seus companheiros Brian May (Gwilyn Lee), Roger Taylor (Ben Hardy) e John Deacon (Joseph Mazzello) mudam o mundo da música para sempre ao formar a banda Queen, durante a década de 1970. Porém, quando o estilo de vida extravagante de Mercury começa a sair do controle, a banda tem que enfrentar o desafio de conciliar a fama e o sucesso com suas vidas pessoais cada vez mais complicadas.', 8);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Blade Runner 2049','', 2017, 'http://br.web.img3.acsta.net/c_310_420/pictures/17/08/25/11/58/463146.jpg', 'Em Blade Runner 2049, após os problemas enfrentados com os Nexus 8, uma nova espécie de replicantes é desenvolvida, de forma que seja mais obediente aos humanos. Um deles é K (Ryan Gosling), um blade runner que caça replicantes foragidos para a polícia de Los Angeles. Após encontrar Sapper Morton (Dave Bautista), K descobre um fascinante segredo: a replicante Rachel (Sean Young) teve um filho, mantido em sigilo até então. A possibilidade de que replicantes se reproduzam pode desencadear uma guerra deles com os humanos, o que faz com que a tenente Joshi (Robin Wright), chefe de K, o envie para encontrar e eliminar a criança.', 10);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Contágio','Nada se espalha como o medo', 2011, 'https://upload.wikimedia.org/wikipedia/pt/8/86/Contagion_Poster.jpg', 'Contágio segue o rápido progresso de um vírus letal, transmissível pelo ar, que mata em poucos dias. Como a epidemia se espalha rapidamente, a comunidade médica mundial inicia uma corrida para encontrar a cura e controlar o pânico que se espalha mais rápido do que o próprio vírus. Ao mesmo tempo, pessoas comuns lutam para sobreviver em uma sociedade que está desmoronando.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O dia depois de amanhã','Onde você vai estar?', 2004, 'https://upload.wikimedia.org/wikipedia/pt/b/bb/The_day_after_tomorrow_poster_promocional.jpg', 'A Terra sofre alterações climáticas que modificam drasticamente a vida da humanidade. Com o norte se resfriando cada vez mais e passando por uma nova era glacial, milhões de sobreviventes rumam para o sul. Porém o paleoclimatologista Jack Hall (Dennis Quaid) segue o caminho inverso e parte para Nova York, já que acredita que seu filho Sam (Jake Gyllenhaal) ainda está vivo.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Apocalypse Now','', 1979, 'https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg', 'O Capitão Willard (Martin Sheen) recebe a missão de encontrar e matar o comandante das Forças Especiais, Coronel Kurtz (Marlon Brando), que aparentemente enlouqueceu e se refugiou nas selvas do Camboja, onde comanda um exército de fanáticos.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Forrest Gump','Forrest Gump - O Contador de Histórias', 1994, 'https://upload.wikimedia.org/wikipedia/pt/thumb/c/c0/ForrestGumpPoster.jpg/240px-ForrestGumpPoster.jpg', 'Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump (Tom Hanks), um rapaz com QI abaixo da média e boas intenções. Por obra do acaso, ele consegue participar de momentos cruciais, como a Guerra do Vietnã e Watergate, mas continua pensando no seu amor de infância, Jenny Curran.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Velozes e Furiosos','', 2001, 'https://upload.wikimedia.org/wikipedia/pt/f/f9/TheFastandtheFurious.jpg', 'Dominic Toretto (Vin Diesel) é o líder de uma gangue de corridas de ruas em Los Angeles que está sendo investigado pela polícia por roubo de equipamentos eletrônicos. Para investigá-lo é enviado Brian O Conner (Paul Walker), que se infiltra na gangue na intenção de descobrir se Toretto é realmente o autor dos crimes ou se há alguém mais por trás deles.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Indiana Jones', 'E os caçadores da Arca Perdida', 1981, 'http://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/91/97/58/20172484.jpg', 'Em 1936, o arqueólogo Indiana Jones (Harrison Ford) é contratado para encontrar a Arca da Aliança, que segundo as escrituras bíblicas conteria "Os Dez Mandamentos" que Deus revelou a Moisés no Monte Horeb. Mas como a lenda diz que o exército que a possuir será invencível, Indiana Jones terá um adversário de peso na busca pela arca perdida: o próprio Adolf Hitler.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Star Wars - Guerra nas estrelas', 'Uma nova esperança', 1978, 'https://upload.wikimedia.org/wikipedia/pt/thumb/7/7e/Star_Wars_Epis%C3%B3dio_IV_Uma_Nova_Esperan%C3%A7a.jpg/243px-Star_Wars_Epis%C3%B3dio_IV_Uma_Nova_Esperan%C3%A7a.jpg', 'Dezenove anos após a formação do Império, o jovem Luke Skywalker entra na luta da Aliança Rebelde e encontra Obi-Wan Kenobi, que inicia o treinamento do rapaz quando ambos embarcam em uma ousada missão para resgatar a bela Princesa Leia, líder dos Rebeldes, de Darth Vader.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Senna', 'O brasileiro, o herói, o campeão', 2010, 'http://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/91/23/19962822.jpg', 'O documentário Senna: O Brasileiro, O Herói, O Campeão conta a história do ídolo brasileiro Ayrton Senna. Em Junho de 1984, GP de Mônaco de Fórmula 1. Seis atuais ou futuros campeões mundiais estavam na pista, mas as atenções ficaram voltadas para um jovem que largara em 13º lugar e estava apenas em sua sexta corrida. Ultrapassando um a um, ele alcançou seu primeiro pódio e apenas não venceu devido a uma questão técnica. Seu nome era Ayrton Senna. Toda trajetória do tricampeão mundial, contada desde a ascensão no automobilismo até sua morte em pleno GP de San Marino, em 1994, passando pela rivalidade com Alain Prost e os problemas enfrentados nos bastidores da Fórmula 1.', 5);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Uma das melhores animações! Muito boa e criativa, boa tanto para crianças quanto para os adultos...', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('A melhor animação já feita!', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme consegue agradar com comédia física,trocadilhos, humor pastelão,piadas sujas,e até humor inteligente,a força do filme está na divisão dos momentos de cada um dos seus personagens carismáticos.', 2, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Gostei, o filme tem muita ação!', 2, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Excelente, um filme sensacional. A direção é ótima, a história é ótima, e a trilha sonora é..... ops, não tem, so percebi ao final do filme, onde você relaxa, toda a tensão do filme acaba e a música vem para te ralaxar. Atuações perfeitas de Javier Bardem e Tommy Lee Jones, e merecidamente o OSCAR de melhor filme. Você tem que assistir esta obra-prima do cinema e se encantar com esse DRAMA épico.', 2, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('A essência do filme é idêntica à HQ criada por Jack Kirby e Stan Lee,o roteiro provou-se à altura do desafio,honra heróis da Marvel com magnificência e explora os pontos fortes dos seus personagens,sensacional em vários quesitos:ação,aventura,diversão e emoção.', 2, 5);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Um dos melhores filmes sobre vírus e epidemia que já assisti. Realmente chega a assustar com a veracidade de fatos.', 2, 8);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Bom filme de desastres apocalípticos, vale a pena é mais um desses filmes, mas pelo menos não tem nenhum meteoro, é original nesse sentido, bom Filme.', 2, 9);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Achei a trilha sonora mais interessante do que o próprio filme para falar a verdade. Para um filme supostamente de guerra, achei que não desenvolveu bem as cenas de ação: além de curtas, não eram intrigantes. O questionamento de bem ou mal é interessante, porém não foi tão bem explorado, ao contrário do que muitos acham. Embora não chegue a ser entediante, é um filme longo com cenas desnecessárias. Acho que daqui uns anos ...', 2, 10);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Sempre que assisto de novo acho melhor do que a ultima vez. Simplesmente genial. Quem critica com filme muito simples igual a nossa colega acima, no mínimo deve desconhecer o escândalo político Watergate, os hippeis dos anos 70, o Smile, O Elvis, o Lennon, a Guerra do Vietnã entre outro eventos. O roteiro engloba tudo isso de uma maneira apenas genial. Run Forrest, run!!!!', 2, 11);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Iniciando bem a franquia, Velozes e Furiosos traz ótimas cenas de ação junto de diversos carros tunados, numa trama simples mas que é sensacional.', 2, 12);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O primeiro grande sucesso da saga Indiana Jones e levou literalmente ao máximo o conceito de gênero aventura, sem apelação a efeitos especiais em demasia. Dos três primeiros esse foi o último que consegui assistir, infelizmente. Um filme rápido, literalmente você ficará preso assistindo a maestria de Jones. Cenas memoráveis como a abertura da arca e também o Jones correndo longe da pedra rolante (essa com certeza é um símbolo do cinema de aventura em todos sentidos marcado para sempre, a cena original). Nesse filme Jones está mais zangado comparado aos demais filmes, para quem assiste fora de ordem ,mas da para dar muita risada com as situações. Um clássico do cinema, indispensável o filme na sua coleção!', 2, 13);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('SENNA Direção: Asif Kapadia Ano: 2010 1h45min Um documentário fantástico que retrata bem, a vida e a morte, do herói nacional chamado Ayrton Senna. Eu que não sou da época, pude contemplar o porquê de tanta reverência ao piloto de Fórmula 1, Ayrton Senna. Não é para menos, ele foi surreal para seu tempo, sendo campeão mundial três vezes seguidas. A todos recomendo esse grande documentário!!', 2, 15);

