INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Documentário');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção Científica');
INSERT INTO tb_genre (name) VALUES ('Musical');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Suspense');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Thriller');

INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Toy Story','Toy Story - Um mundo de aventuras', 1995, 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/6AafgfifXkFS4g2xGJZIwsPQK6P.jpg', 'O aniversário do garoto Andy está chegando e seus brinquedos ficam nervosos, temendo que ele ganhe novos brinquedos que possam substituí-los. Liderados pelo caubói Woody, o brinquedo predileto de Andy, eles recebem Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Com ciúmes, Woody tenta ensiná-lo uma lição, mas Buzz cai pela janela. É o início da aventura do caubói, que precisa resgatar Buzz para limpar sua barra com os outros brinquedos.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Loucademia de Polícia','What an Institution', 1984, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'O prefeito resolve mudar a lei, afirmando que fatores como sexo, peso e inteligência não devem influenciar nas aplicações para a força policial. Liderado por Carey Mahoney, um grupo de jovens incompetentes, mas de bom coração, ingressa na Academia de Polícia para o desespero dos instrutores, que buscarão impedir de toda as formas as brincadeiras da turma.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Escorpião Rei','Guerreiro, Lenda, Rei', 2002, 'https://3.bp.blogspot.com/-blPP-TXQVHo/VMVOkRLcmrI/AAAAAAAAAxM/zPi9f_j_obk/s1600/filme%2Bo%2Bescorpi%C3%A3o%2Brei.jpg', 'Menom, um governante maligno, está conquistando muitos reinos com a ajuda de uma feiticeira que pode prever o sucesso ou fracasso da missão. Com isso, várias tribos inimigas se unem a fim de contratar um eficaz assassino que poderá eliminar a feiticeira. Este assassino é um acadiano, Mathayus. Com a ajuda de um ladrão de cavalos e da feiticeira, que se tornou sua aliada, eles vão combater Menom e seu exército.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Onde os fracos não tem vez','Um filme dos irmãos Cohen', 2008, 'https://br.web.img3.acsta.net/pictures/210/079/21007978_20130523175557996.jpg', 'Texas, década de 80. Um traficante de drogas é encontrado no deserto por um caçador pouco esperto, Llewelyn Moss (Josh Brolin), que pega uma valise cheia de dinheiro mesmo sabendo que em breve alguém irá procurá-lo devido a isso. Logo Anton Chigurh (Javier Bardem), um assassino psicótico sem senso de humor e piedade, é enviado em seu encalço. Porém para alcançar Moss ele precisará passar pelo xerife local, Ed Tom Bell (Tommy Lee Jones).', 6);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Os Vingadores','The Avengers', 2012, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'Loki (Tom Hiddleston) retorna à Terra enviado pelos chitauri, uma raça alienígena que pretende dominar os humanos. Com a promessa de que será o soberano do planeta, ele rouba o cubo cósmico dentro de instalações da S.H.I.E.L.D. e, com isso, adquire grandes poderes. Loki os usa para controlar o dr. Erik Selvig (Stellan Skarsgard) e Clint Barton/Gavião Arqueiro (Jeremy Renner), que passam a trabalhar para ele. No intuito de contê-los, Nick Fury (Samuel L. Jackson) convoca um grupo de pessoas com grandes habilidades, mas que jamais haviam trabalhado juntas: Tony Stark/Homem de Ferro (Robert Downey Jr.), Steve Rogers/Capitão América (Chris Evans), Thor (Chris Hemsworth), Bruce Banner/Hulk (Mark Ruffalo) e Natasha Romanoff/Viúva Negra (Scarlett Johansson). Só que, apesar do grande perigo que a Terra corre, não é tão simples assim conter o ego e os interesses de cada um deles para que possam agir em grupo.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Bohemian Rhapsody','A única coisa mais extraordinária do que a sua música é a sua história', 2018, 'http://br.web.img3.acsta.net/c_310_420/pictures/18/08/24/21/29/2341995.jpg', 'Freddie Mercury (Rami Malek) e seus companheiros Brian May (Gwilyn Lee), Roger Taylor (Ben Hardy) e John Deacon (Joseph Mazzello) mudam o mundo da música para sempre ao formar a banda Queen, durante a década de 1970. Porém, quando o estilo de vida extravagante de Mercury começa a sair do controle, a banda tem que enfrentar o desafio de conciliar a fama e o sucesso com suas vidas pessoais cada vez mais complicadas.', 8);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Blade Runner 2049','', 2017, 'http://br.web.img3.acsta.net/c_310_420/pictures/17/08/25/11/58/463146.jpg', 'Em Blade Runner 2049, após os problemas enfrentados com os Nexus 8, uma nova espécie de replicantes é desenvolvida, de forma que seja mais obediente aos humanos. Um deles é K (Ryan Gosling), um blade runner que caça replicantes foragidos para a polícia de Los Angeles. Após encontrar Sapper Morton (Dave Bautista), K descobre um fascinante segredo: a replicante Rachel (Sean Young) teve um filho, mantido em sigilo até então. A possibilidade de que replicantes se reproduzam pode desencadear uma guerra deles com os humanos, o que faz com que a tenente Joshi (Robin Wright), chefe de K, o envie para encontrar e eliminar a criança.', 10);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Loucademia de Polícia','What an Institution', 1984, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'O prefeito resolve mudar a lei, afirmando que fatores como sexo, peso e inteligência não devem influenciar nas aplicações para a força policial. Liderado por Carey Mahoney, um grupo de jovens incompetentes, mas de bom coração, ingressa na Academia de Polícia para o desespero dos instrutores, que buscarão impedir de toda as formas as brincadeiras da turma.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Loucademia de Polícia','What an Institution', 1984, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'O prefeito resolve mudar a lei, afirmando que fatores como sexo, peso e inteligência não devem influenciar nas aplicações para a força policial. Liderado por Carey Mahoney, um grupo de jovens incompetentes, mas de bom coração, ingressa na Academia de Polícia para o desespero dos instrutores, que buscarão impedir de toda as formas as brincadeiras da turma.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Loucademia de Polícia','What an Institution', 1984, 'https://upload.wikimedia.org/wikipedia/pt/d/dc/Police_Academy.jpg', 'O prefeito resolve mudar a lei, afirmando que fatores como sexo, peso e inteligência não devem influenciar nas aplicações para a força policial. Liderado por Carey Mahoney, um grupo de jovens incompetentes, mas de bom coração, ingressa na Academia de Polícia para o desespero dos instrutores, que buscarão impedir de toda as formas as brincadeiras da turma.', 4); 

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Uma das melhores animações! Muito boa e criativa, boa tanto para crianças quanto para os adultos...', 1, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme consegue agradar com comédia física,trocadilhos,humor pastelão,piadas sujas,e até humor inteligente,a força do filme está na divisão dos momentos de cada um dos seus personagens carismáticos.', 1, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Excelente, um filme sensacional. A direção é ótima, a história é ótima, e a trilha sonora é..... ops, não tem, so percebi ao final do filme, onde você relaxa, toda a tensão do filme acaba e a música vem para te ralaxar. Atuações perfeitas de Javier Bardem e Tommy Lee Jones, e merecidamente o OSCAR de melhor filme. Você tem que assistir esta obra-prima do cinema e se encantar com esse DRAMA épico.', 2, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('A essência do filme é idêntica à HQ criada por Jack Kirby e Stan Lee,o roteiro provou-se à altura do desafio,honra heróis da Marvel com magnificência e explora os pontos fortes dos seus personagens,sensacional em vários quesitos:ação,aventura,diversão e emoção.', 1, 5);